### ISSUE TITLE
getting: Forgot to register a type adapter?

### ISSUE THREAD

**Issue by Isabellle** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#17]
Here is the error:

`java.lang.UnsupportedOperationException: Attempted to serialize
java.lang.Class: com.ilepez.weatherapp.data.model.CityArrayList. Forgot to register a type adapter?
at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:76)
at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:69)
at com.google.gson.Gson.toJson(Gson.java:669)
at com.google.gson.Gson.toJson(Gson.java:648)
at com.google.gson.Gson.toJson(Gson.java:603)
at com.google.gson.Gson.toJson(Gson.java:583)
at com.ilepez.weatherapp.utils.TinyDB.putObject(TinyDB.java:462)
at com.ilepez.weatherapp.activity.SearchActivity.onItemClick(SearchActivity.java:67)
at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:928)
at android.widget.AutoCompleteTextView.access$500(AutoCompleteTextView.java:93)
at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1230)
at android.widget.AdapterView.performItemClick(AdapterView.java:345)
at android.widget.AbsListView.performItemClick(AbsListView.java:1547)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3821)
at android.widget.AbsListView$3.run(AbsListView.java:5841)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
    07-17 10:55:26.283 15392-15392/com.ilepez.weatherapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)`

The full explanation can be found here: [http://stackoverflow.com/questions/38419555/tinydb-sharedpreferences-getting-forgot-to-register-a-type-adapter](url)

**Comment by kcochibili** [comment]
You are passing in the wrong thing. the putObject method requires you to pass in a String key and an already instantiated object, not a class type.
check my response to your question on http://stackoverflow.com/a/38427788/1463931

**Comment by Isabellle** [comment]
Thanks @kcochibili , problem solved. Not related at all with your lib.

**Comment by MohiniRajendraGawale** [comment]
Hi Isabelle,

Could you please explain here what you did to get this error resolved?
I am stuck at this error and not getting anything to clear it.

**Comment by kcochibili** [comment]
@MohiniRajendraGawale 
Have you looked at my example here?
 http://stackoverflow.com/a/38427788/1463931

Also you should post the exact error you're getting. So that I can properly help you.
