### ISSUE TITLE
Using Joda DateTime in my custom object

### ISSUE THREAD

**Issue by tarchen** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#35]
Is there any way to modify the tinyDB class to be able to save a custom object with a DateTime field. I tried adding the following:
` private class DateTimeSerializer implements JsonSerializer<DateTime> {
        public JsonElement serialize(DateTime src, Type typeOfSrc, JsonSerializationContext context) {
            return new JsonPrimitive(src.toString());
        }
    }

    private class DateTimeDeserializer implements JsonDeserializer<DateTime> {
        public DateTime deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
                throws JsonParseException {
            return new DateTime(json.getAsJsonPrimitive().getAsString());
        }
    }

    public void retrieveGlobalDataFromStorage(Context context) {
// ...

        final GsonBuilder builder = new GsonBuilder();
        builder.registerTypeAdapter(DateTime.class, new DateTimeSerializer());
        builder.registerTypeAdapter(DateTime.class, new DateTimeDeserializer());

        final Gson gson = builder.create();
// ...
    }` but I am still getting a fatal exception 
Caused by: java.lang.RuntimeException: Failed to invoke public org.joda.time.Chronology() with no args
                                                                   at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                                   at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                   at com.google.gson.Gson.fromJson(Gson.java:852)
                                                                   at com.google.gson.Gson.fromJson(Gson.java:801)
                                                                   at com.google.gson.Gson.fromJson(Gson.java:773)
                                                                   at dtcj.badgerme.TinyDB.getListObject(TinyDB.java:358)

Thanks for any advice!
Taryn

**Comment by kcochibili** [comment]
Using this Converter:
github.com/gkopff/gson-javatime-serialisers

do something like this github.com/JodaOrg/joda-time/issues/294#issuecomment-112861907

The suggestion above is from a quick google search, I did not test it.
